/**
 * lib/clustering.ts
 * Takes a flat ArchitectureGraph and returns an enriched version where
 * nodes carry parentGroup info, and groups are represented as container nodes.
 *
 * Groups can come from Gemini (preferred) or be auto-generated by category.
 */

import type { GraphNode, ArchitectureGraph, GraphGroup } from './prompts';

export interface PositionedGroup {
  id: string;
  label: string;
  description: string;
  category: GraphNode['data']['category'];
  nodeIds: string[];
  /** Bounding box computed after layout */
  x: number;
  y: number;
  width: number;
  height: number;
}

const GROUP_PADDING = 40; // px padding inside group container
const NODE_WIDTH = 220;
const NODE_HEIGHT = 110;
const NODE_GAP = 24;
const GROUP_HEADER_HEIGHT = 48;

/**
 * Auto-cluster nodes by category when Gemini doesn't provide explicit groups.
 */
export function autoCluster(nodes: GraphNode[]): GraphGroup[] {
  const byCategory = new Map<string, string[]>();

  for (const node of nodes) {
    const cat = node.data.category;
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat)!.push(node.id);
  }

  const CATEGORY_LABELS: Record<string, string> = {
    frontend: 'Frontend',
    backend: 'Backend / API',
    database: 'Data Layer',
    infrastructure: 'Infrastructure & Deployment',
    external: 'External Services',
    mobile: 'Mobile',
    user: 'User / Actor',
    process: 'Process / Step',
    mockup: 'UI / Screen',
  };

  const groups: GraphGroup[] = [];
  let idx = 0;
  for (const [cat, nodeIds] of byCategory.entries()) {
    if (nodeIds.length === 0) continue;
    groups.push({
      id: `group-${cat}`,
      label: CATEGORY_LABELS[cat] ?? cat,
      description: '',
      category: cat as GraphNode['data']['category'],
      nodeIds,
    });
    idx++;
  }

  return groups;
}

/**
 * Given groups and nodes, compute positions for every group and its children.
 * Groups are laid out in a rough grid; children are arranged in rows inside.
 *
 * Returns:
 * - `groupNodes`: React Flow nodes of type "groupNode" (the container)
 * - `updatedNodes`: Original nodes with corrected `position` (relative to parent)
 *   and `parentNode` + `extent` set for React Flow's parent/child system.
 */
export function layoutWithGroups(
  groups: GraphGroup[],
  nodes: GraphNode[]
): { groupNodes: GraphNode[]; updatedNodes: GraphNode[] } {
  const nodeMap = new Map(nodes.map((n) => [n.id, n]));

  const COLS = Math.ceil(Math.sqrt(groups.length));
  const GROUP_COL_GAP = 80;
  const GROUP_ROW_GAP = 80;

  const groupNodes: GraphNode[] = [];
  const updatedNodes: GraphNode[] = [];

  // Track which nodes were assigned to groups
  const assignedIds = new Set<string>();

  groups.forEach((group, gi) => {
    const validNodeIds = group.nodeIds.filter((id) => nodeMap.has(id));
    if (validNodeIds.length === 0) return;

    // Compute group size based on children
    const nodesPerRow = Math.ceil(Math.sqrt(validNodeIds.length));
    const cols = Math.min(nodesPerRow, validNodeIds.length);
    const rows = Math.ceil(validNodeIds.length / cols);

    const groupWidth =
      GROUP_PADDING * 2 + cols * NODE_WIDTH + (cols - 1) * NODE_GAP;
    const groupHeight =
      GROUP_PADDING * 2 +
      GROUP_HEADER_HEIGHT +
      rows * NODE_HEIGHT +
      (rows - 1) * NODE_GAP;

    // Group position in the grid
    const col = gi % COLS;
    const row = Math.floor(gi / COLS);
    const gx =
      col * (groupWidth + GROUP_COL_GAP) + (col > 0 ? GROUP_COL_GAP : 0);
    const gy =
      row * (groupHeight + GROUP_ROW_GAP) + (row > 0 ? GROUP_ROW_GAP : 0);

    // Accumulater offset for grid
    // (simplified: real impl uses iterative width tracking)
    groupNodes.push({
      id: group.id,
      type: 'groupNode' as any,
      position: { x: gx, y: gy },
      data: {
        label: group.label,
        subtitle: group.description || '',
        description: group.description || '',
        category: group.category,
        tech: '',
        confidence: 'confirmed',
      } as any,
      // React Flow group sizing
      style: {
        width: groupWidth,
        height: groupHeight,
      },
    } as GraphNode);

    // Position children relative to group
    validNodeIds.forEach((nodeId, ni) => {
      const original = nodeMap.get(nodeId)!;
      const c = ni % cols;
      const r = Math.floor(ni / cols);
      const childX = GROUP_PADDING + c * (NODE_WIDTH + NODE_GAP);
      const childY = GROUP_PADDING + GROUP_HEADER_HEIGHT + r * (NODE_HEIGHT + NODE_GAP);

      updatedNodes.push({
        ...original,
        position: { x: childX, y: childY },
        // React Flow parent/child system
        parentNode: group.id,
        extent: 'parent',
      } as any);

      assignedIds.add(nodeId);
    });
  });

  // Any nodes not in a group get placed below all groups (orphans)
  const orphans = nodes.filter((n) => !assignedIds.has(n.id));
  orphans.forEach((n, i) => {
    updatedNodes.push({
      ...n,
      position: { x: i * (NODE_WIDTH + NODE_GAP), y: 1200 },
    });
  });

  return { groupNodes, updatedNodes };
}
